services:
  hackernews-db:
    image: postgres:latest
    container_name: hackernews-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackernewsdb
    ports:
      - "5432:5432"
    volumes:
      - hackernews-data:/var/lib/postgresql:rw
    networks:
      - hackernews-network

networks:
  hackernews-network:
    name: hackernews-network
    driver: bridge

volumes:
  hackernews-data:
    name: hackernews-data
