services:
  hackernews-db:
    image: postgres:latest
    container_name: hackernews-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=hackernewsdb
    ports:
      - "5434:5432"
    volumes:
      - hackernews-volume:/var/lib/postgresql/data
    networks:
      - hackernews-network

networks:
  hackernews-network:
    name: hackernews-network
    driver: bridge

volumes:
  hackernews-volume:
    name: hackernews_volume